### ISSUE TITLE
The links for How to build PaddlePaddle for mobile are broken

### ISSUE THREAD

**Issue by jetfuel** [PaddlePaddle/Mobile#23]
There are two links under How to build PaddlePaddle for mobile. They are

- Build PaddlePaddle for Android
- Build PaddlePaddle for Raspberry Pi3

And they are both broken right now. This might relate to the recent rearrangement in Paddle.

**Comment by lk1ngaa7** [comment]
@jetfuel you can find here https://github.com/PaddlePaddle/Paddle/tree/develop/doc/mobile

**Comment by Xreki** [comment]
@jetfuel I renamed `doc/howto/cross_compiling` into `doc/mobile` as discussed in https://github.com/PaddlePaddle/Paddle/issues/5168. The links are fixed in #24 .
Now the building documentation can also be shown on the website now:
- http://doc.paddlepaddle.org/develop/doc_cn/mobile/index_cn.html
- http://doc.paddlepaddle.org/develop/doc/mobile/index_en.html
